@echo off
setlocal EnableExtensions EnableDelayedExpansion
rem Generated by scripts\windows\setup_hermes_windows.ps1 (edit there, then re-run setup).
for %%I in ("%~dp0.") do set "WIN_DIR=%%~fI"
for %%I in ("%WIN_DIR%\..") do set "REPO_ROOT=%%~fI"
cd /d "%REPO_ROOT%"

chcp 65001 >nul
set "PYTHONIOENCODING=utf-8"

for /F "tokens=1,2 delims=#" %%a in ('"prompt #$H#$E# & echo on & for %%b in (1) do rem"') do set "ESC=%%b"
rem Logo: alles wit (bright white)
set "G=%ESC%[97m"
set "C=%ESC%[97m"
set "M=%ESC%[97m"
set "W=%ESC%[97m"
set "R=%ESC%[0m"

echo %C%+------------------------------------------------------------------+%R%
echo %C%^|%R%  %G%  __  __                                 %M% ____  %R%               %C%^|%R%
echo %C%^|%R%  %G% ^|  ^|/  ^| ___ _ __ _ __ ___   ___       %M%^|_   ^| _____  ___ %R%   %C%^|%R%
echo %C%^|%R%  %G% ^| ^|^| ^| ^|/ _ \ '__^| '_ ` _ \ / _ \%R%        %M% ^| ^| ^|/ _ \ \/ /%R%   %C%^|%R%
echo %C%^|%R%  %G% ^| ^|  ^| ^|  __/^| ^| ^| ^| ^| ^| ^| (_) ^|%R%        %M% ^| ^| ^| (_) ^>  ^< %R%   %C%^|%R%
echo %C%^|%R%  %G% ^|_^|  ^|_^|\___^|_^|_^| ^|_^|_^|_^|\___/%R%        %M% ^|_^|_^|\___/_/\_\%R%   %C%^|%R%
echo %C%^|%R%  %W%Hermes Agent - Windows%R%                                      %C%^|%R%
echo %C%+------------------------------------------------------------------+%R%
echo.

if exist "%WIN_DIR%\launch_hermes.bat" (
  call "%WIN_DIR%\launch_hermes.bat" %*
  exit /b !ERRORLEVEL!
)

if exist "%REPO_ROOT%\.venv\Scripts\python.exe" (
  echo %C%[INFO]%R% No launch_hermes.bat - starting via .venv\python cli.py
  "%REPO_ROOT%\.venv\Scripts\python.exe" "%REPO_ROOT%\cli.py" %*
  exit /b !ERRORLEVEL!
)

echo [ERROR] Missing launch_hermes.bat and .venv\Scripts\python.exe. Run install.ps1 or uv sync.
exit /b 1
