#requires -Version 5.1
<#
.SYNOPSIS
  Windows-setup: schrijft lokale bestanden onder <repo>\windows\ (gitignored) en
  optioneel snelkoppelingen (Desktop + taakbalk-stijl in windows\).

.DESCRIPTION
  - Maakt windows\Hermes_met_logo.bat (ANSI wit logo; roept launch_hermes.bat aan).
  - Schrijft windows\setup_hermes_windows.bat en windows\hermes_update.bat.
  - Genereert hermes_taskbar_white.ico (wit monogram) en gebruikt die voor alle nieuwe .lnk.
  - Hermes - setup Windows / Hermes - update / **Open Setup** (naar taakbalk slepen).lnk in windows\.
  - Minimaal launch_hermes.bat alleen als het nog ontbreekt (tenzij -ForceLaunchBat).
  - Desktop: **Hermes Agent.lnk** + **Hermes Open Setup.lnk** tenzij -NoShortcut.

  Draai altijd de **.bat** vanuit Explorer (dubbelklik op .ps1 gebruikt vaak Restricted policy).

  - Optioneel: volledige **hermes setup --full** na de Windows-bestanden via **OPEN_SETUP.bat**
    ^(zelfde cmd + zelfde Conda/.venv-Python als launch_hermes.bat^). Dubbelklik: **windows\OPEN_SETUP.bat**.

  Triggers: -FullSetup, HERMES_SETUP_FULL_SETUP=1, of op setup-batch: **--full-setup**.

  Na interactieve setup start **Hermes automatisch** in een nieuw cmd-venster (Hermes_met_logo.bat),
  tenzij de omgeving **HERMES_SETUP_NO_LAUNCH** is gezet.
#>
param(
    [string]$RepoRoot = "",
    [switch]$NoShortcut,
    [switch]$NoTaskbarLinks,
    [switch]$ForceLogoBat,
    [switch]$ForceLaunchBat,
    [switch]$FullSetup,
    [switch]$WhatIf
)

$ErrorActionPreference = "Stop"

function Resolve-RepoRoot {
    param([string]$Explicit)
    if ($Explicit -and (Test-Path -LiteralPath $Explicit)) {
        return (Resolve-Path -LiteralPath $Explicit).Path
    }
    $here = $PSScriptRoot
    $candidate = Resolve-Path (Join-Path $here "..\..") | Select-Object -ExpandProperty Path
    if (Test-Path -LiteralPath (Join-Path $candidate "cli.py")) {
        return $candidate
    }
    throw "Repo-root niet gevonden. Geef -RepoRoot mee (map met cli.py)."
}

function Write-LogoBat {
    param(
        [string]$WindowsDir,
        [switch]$WhatIf
    )
    $path = Join-Path $WindowsDir "Hermes_met_logo.bat"
    $bat = @'
@echo off
setlocal EnableExtensions EnableDelayedExpansion
rem Generated by scripts\windows\setup_hermes_windows.ps1 (edit there, then re-run setup).
for %%I in ("%~dp0.") do set "WIN_DIR=%%~fI"
for %%I in ("%WIN_DIR%\..") do set "REPO_ROOT=%%~fI"
cd /d "%REPO_ROOT%"

chcp 65001 >nul
set "PYTHONIOENCODING=utf-8"

for /F "tokens=1,2 delims=#" %%a in ('"prompt #$H#$E# & echo on & for %%b in (1) do rem"') do set "ESC=%%b"
rem Logo: alles wit (bright white)
set "G=%ESC%[97m"
set "C=%ESC%[97m"
set "M=%ESC%[97m"
set "W=%ESC%[97m"
set "R=%ESC%[0m"

echo %C%+------------------------------------------------------------------+%R%
echo %C%^|%R%  %G%  __  __                                 %M% ____  %R%               %C%^|%R%
echo %C%^|%R%  %G% ^|  ^|/  ^| ___ _ __ _ __ ___   ___       %M%^|_   ^| _____  ___ %R%   %C%^|%R%
echo %C%^|%R%  %G% ^| ^|^| ^| ^|/ _ \\ '__^| '_ ` _ \\ / _ \\%R%        %M% ^| ^| ^|/ _ \\ \\/ /%R%   %C%^|%R%
echo %C%^|%R%  %G% ^| ^|  ^| ^|  __/^| ^| ^| ^| ^| ^| ^| (_) ^|%R%        %M% ^| ^| ^| (_) ^>  ^< %R%   %C%^|%R%
echo %C%^|%R%  %G% ^|_^|  ^|_^|\\___^|_^|_^| ^|_^|_^|_^|\\___/%R%        %M% ^|_^|_^|\\___/_/\\_\\%R%   %C%^|%R%
echo %C%^|%R%  %W%Hermes Agent - Windows%R%                                      %C%^|%R%
echo %C%+------------------------------------------------------------------+%R%
echo.

if exist "%WIN_DIR%\launch_hermes.bat" (
  call "%WIN_DIR%\launch_hermes.bat" %*
  exit /b !ERRORLEVEL!
)

if exist "%REPO_ROOT%\.venv\Scripts\python.exe" (
  echo %C%[INFO]%R% No launch_hermes.bat - starting via .venv\python cli.py
  "%REPO_ROOT%\.venv\Scripts\python.exe" "%REPO_ROOT%\cli.py" %*
  exit /b !ERRORLEVEL!
)

echo [ERROR] Missing launch_hermes.bat and .venv\Scripts\python.exe. Run install.ps1 or uv sync.
exit /b 1
'@
    if ($WhatIf) {
        Write-Host ('[WhatIf] Zou schrijven: ' + $path)
        return
    }
    Set-Content -LiteralPath $path -Value $bat -Encoding ASCII
}

function Write-MinimalLaunchBat {
    param(
        [string]$WindowsDir,
        [string]$RepoRootPath,
        [switch]$WhatIf
    )
    $path = Join-Path $WindowsDir "launch_hermes.bat"
    $bat = @"
@echo off
setlocal EnableExtensions EnableDelayedExpansion
rem Minimaal gegenereerd door scripts\windows\setup_hermes_windows.ps1 (alleen als bestand ontbrak).
set "WIN_SCR=%~dp0"
for %%I in ("%WIN_SCR%..") do set "REPO_ROOT=%%~fI"
cd /d "%REPO_ROOT%"

if not defined HERMES_LANCEDB_PATH set "HERMES_LANCEDB_PATH=%USERPROFILE%\data\my_lancedb"
if not defined HERMES_RAG_RAW_SOURCE set "HERMES_RAG_RAW_SOURCE=%USERPROFILE%\data\raw_source_files"

if not defined HERMES_CONDA_ENV set "HERMES_CONDA_ENV=hermes-env"
if not defined HERMES_PYTHON if exist "%USERPROFILE%\miniconda3\envs\!HERMES_CONDA_ENV!\python.exe" set "HERMES_PYTHON=%USERPROFILE%\miniconda3\envs\!HERMES_CONDA_ENV!\python.exe"
if not defined HERMES_PYTHON if exist "%USERPROFILE%\anaconda3\envs\!HERMES_CONDA_ENV!\python.exe" set "HERMES_PYTHON=%USERPROFILE%\anaconda3\envs\!HERMES_CONDA_ENV!\python.exe"
if not defined HERMES_PYTHON if exist "%LOCALAPPDATA%\miniconda3\envs\!HERMES_CONDA_ENV!\python.exe" set "HERMES_PYTHON=%LOCALAPPDATA%\miniconda3\envs\!HERMES_CONDA_ENV!\python.exe"
if not defined HERMES_PYTHON if exist "%LOCALAPPDATA%\anaconda3\envs\!HERMES_CONDA_ENV!\python.exe" set "HERMES_PYTHON=%LOCALAPPDATA%\anaconda3\envs\!HERMES_CONDA_ENV!\python.exe"
if defined HERMES_PYTHON set "HERMES_PYTHON_ENV=!HERMES_PYTHON!"

if exist "%REPO_ROOT%\.venv\Scripts\python.exe" (
  set "HERMES_PYTHON=%REPO_ROOT%\.venv\Scripts\python.exe"
  set "HERMES_PYTHON_ENV=!HERMES_PYTHON!"
)

chcp 65001 >nul
set "PYTHONIOENCODING=utf-8"
if defined HERMES_PYTHON echo [INFO] HERMES_PYTHON=!HERMES_PYTHON!

if not defined HERMES_PYTHON (
  echo [ERROR] Geen HERMES_PYTHON en geen .venv. Installeer deps: zie CONTRIBUTING.md
  pause
  exit /b 1
)

"%HERMES_PYTHON%" "%REPO_ROOT%\cli.py" %*
exit /b %ERRORLEVEL%
"@
    if ($WhatIf) {
        Write-Host ('[WhatIf] Zou schrijven: ' + $path)
        return
    }
    Set-Content -LiteralPath $path -Value $bat -Encoding ASCII
}

function Get-HermesWhiteShortcutIcon {
    param(
        [string]$WindowsDir,
        [switch]$WhatIf
    )
    $ico = Join-Path $WindowsDir "hermes_taskbar_white.ico"
    if ($WhatIf) {
        return ($ico + ",0")
    }
    try {
        Add-Type -AssemblyName System.Drawing -ErrorAction Stop
        $size = 48
        $bmp = New-Object System.Drawing.Bitmap ($size), ($size), ([System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        $g = [System.Drawing.Graphics]::FromImage($bmp)
        $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
        $g.Clear([System.Drawing.Color]::FromArgb(0, 0, 0, 0))
        $pen = New-Object System.Drawing.Pen ([System.Drawing.Color]::White, 5)
        $pen.StartCap = [System.Drawing.Drawing2D.LineCap]::Round
        $pen.EndCap = [System.Drawing.Drawing2D.LineCap]::Round
        $g.DrawLine($pen, 10, 8, 10, 40)
        $g.DrawLine($pen, 32, 8, 32, 40)
        $g.DrawLine($pen, 10, 24, 32, 24)
        $pen.Dispose()
        $g.Dispose()
        $icon = [System.Drawing.Icon]::FromHandle($bmp.GetHicon())
        try {
            $fs = [System.IO.File]::Create($ico)
            $icon.Save($fs)
            $fs.Close()
        } finally {
            $icon.Dispose()
            $bmp.Dispose()
        }
        return ($ico + ",0")
    } catch {
        Write-Warning ("Witte .ico niet gegenereerd (" + $_.Exception.Message + "); fallback imageres.")
        return ($env:SystemRoot + "\System32\imageres.dll,1")
    }
}

function New-ShellShortcut {
    param(
        [string]$LnkPath,
        [string]$TargetPath,
        [string]$Arguments,
        [string]$WorkDir,
        [string]$IconLocation,
        [string]$Description,
        [switch]$WhatIf
    )
    if ($WhatIf) {
        Write-Host ('[WhatIf] Snelkoppeling: ' + $LnkPath)
        return
    }
    $w = New-Object -ComObject WScript.Shell
    $s = $w.CreateShortcut($LnkPath)
    $s.TargetPath = $TargetPath
    $s.Arguments = $Arguments
    $s.WorkingDirectory = $WorkDir
    $s.WindowStyle = 1
    if ($IconLocation) { $s.IconLocation = $IconLocation }
    if ($Description) { $s.Description = $Description }
    $s.Save()
}

function Write-WindowsSetupCmdBat {
    param([string]$WindowsDir, [switch]$WhatIf)
    $path = Join-Path $WindowsDir "setup_hermes_windows.bat"
    $bat = @'
@echo off
setlocal EnableExtensions EnableDelayedExpansion
set "HERMES_WINDOWS_BAT_PARENT=1"
set "PSX=%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe"
if not exist "%PSX%" set "PSX=powershell.exe"
cd /d "%~dp0.."
if not exist "cli.py" (
  echo [ERROR] Geen repo-root: cli.py ontbreekt na cd naar:
  cd
  pause
  exit /b 1
)
if not exist "%~dp0..\scripts\windows\setup_hermes_windows.ps1" (
  echo [ERROR] Kan setup-script niet vinden:
  echo   "%~dp0..\scripts\windows\setup_hermes_windows.ps1"
  pause
  exit /b 1
)
echo [Hermes] Start setup ^(repo: %CD%^)...
set "PSARGS=%*"
echo(%*| findstr /I "full-setup" >nul && set "HERMES_SETUP_FULL_SETUP=1"
if defined PSARGS (
  set "PSARGS=!PSARGS:--quiet=!"
  set "PSARGS=!PSARGS:--QUIET=!"
  set "PSARGS=!PSARGS:--full-setup=!"
  set "PSARGS=!PSARGS:--FULL-SETUP=!"
)
"%PSX%" -NoProfile -ExecutionPolicy Bypass -File "%~dp0..\scripts\windows\setup_hermes_windows.ps1" !PSARGS!
set ERR=!ERRORLEVEL!
if !ERR! neq 0 (
  echo.
  echo [ERROR] Setup stopte met code !ERR!
  set "HERMES_WINDOWS_BAT_PARENT="
  pause
  exit /b !ERR!
)
if defined HERMES_SETUP_SILENT (
  set "HERMES_WINDOWS_BAT_PARENT="
  exit /b 0
)
if /I "%~1"=="--quiet" (
  set "HERMES_WINDOWS_BAT_PARENT="
  exit /b 0
)
if defined HERMES_SETUP_FULL_SETUP (
  echo.
  echo [Hermes] Volledige configuratiewizard ^(OPEN_SETUP.bat — zelfde Python als launch_hermes^)...
  set "HERMES_OPEN_SETUP_NOPAUSE=1"
  call "%~dp0OPEN_SETUP.bat"
  set "HERMES_OPEN_SETUP_NOPAUSE="
  set "WIZ=!ERRORLEVEL!"
  if !WIZ! neq 0 (
    set "HERMES_WINDOWS_BAT_PARENT="
    pause
    exit /b !WIZ!
  )
)
set "HERMES_WINDOWS_BAT_PARENT="
echo.
echo [OK] Setup klaar. Hermes opent in een nieuw venster ^(zelfde als de Desktop-snelkoppeling^).
echo Interactieve prompt hieronder voor aanpassingen ^(typ exit als klaar^).
echo.
if not defined HERMES_SETUP_NO_LAUNCH (
  if exist "windows\Hermes_met_logo.bat" (
    start "Hermes Agent" cmd /k "cd /d ""!CD!"" && call windows\Hermes_met_logo.bat"
  ) else if exist "windows\launch_hermes.bat" (
    start "Hermes Agent" cmd /k "cd /d ""!CD!"" && call windows\launch_hermes.bat"
  )
)
cmd /k "cd /d ""!CD!"" && title Hermes Agent repo && echo [Hermes] Repo-map: && cd && echo. && echo Voorbeelden:  notepad windows\launch_hermes.bat   explorer windows"
exit /b 0
'@
    if ($WhatIf) {
        Write-Host ('[WhatIf] Zou schrijven: ' + $path)
        return
    }
    Set-Content -LiteralPath $path -Value $bat -Encoding ASCII
}

function Write-HermesUpdateCmdBat {
    param([string]$WindowsDir, [switch]$WhatIf)
    $path = Join-Path $WindowsDir "hermes_update.bat"
    $bat = @'
@echo off
setlocal EnableExtensions
rem Doorverwijzing naar UPDATE_HERMES.bat (preflight + upstream_sync.ps1 -Phase Update)
cd /d "%~dp0.."
if not exist "%~dp0UPDATE_HERMES.bat" (
  echo [ERROR] UPDATE_HERMES.bat ontbreekt in windows\
  pause
  exit /b 1
)
call "%~dp0UPDATE_HERMES.bat" %*
exit /b %ERRORLEVEL%
'@
    if ($WhatIf) {
        Write-Host ('[WhatIf] Zou schrijven: ' + $path)
        return
    }
    Set-Content -LiteralPath $path -Value $bat -Encoding ASCII
}

function Invoke-HermesFullSetupWizard {
    param(
        [Parameter(Mandatory = $true)][string]$RepoRoot,
        [switch]$WhatIf
    )
    if ($WhatIf) {
        Write-Host "[WhatIf] Zou 'hermes setup --full' starten in repo." -ForegroundColor Yellow
        return 0
    }
    $hermesExe = $null
    foreach ($name in @('hermes.exe', 'hermes.cmd')) {
        $p = Join-Path $RepoRoot (Join-Path '.venv\Scripts' $name)
        if (Test-Path -LiteralPath $p) {
            $hermesExe = $p
            break
        }
    }
    if (-not $hermesExe) {
        try {
            $cmd = Get-Command hermes -ErrorAction Stop
            if ($cmd.Path) { $hermesExe = $cmd.Path }
        } catch { }
    }
    if (-not $hermesExe -or -not (Test-Path -LiteralPath $hermesExe)) {
        Write-Host "[ERROR] hermes-CLI niet gevonden (.venv\Scripts noch PATH). Installeer deps / venv, daarna: hermes setup --full" -ForegroundColor Red
        return 1
    }
    Write-Host ""
    Write-Host "[Hermes] Start installatiewizard (hermes setup --full) ..." -ForegroundColor Cyan
    Push-Location $RepoRoot
    try {
        & $hermesExe setup --full
        $code = $LASTEXITCODE
        if ($null -eq $code) { return 0 }
        return $code
    } finally {
        Pop-Location
    }
}

function New-DesktopShortcut {
    param(
        [string]$TargetBat,
        [string]$WorkDir,
        [string]$IconLocation,
        [switch]$WhatIf
    )
    $desktop = [Environment]::GetFolderPath("Desktop")
    if (-not $desktop) { return }
    $lnkPath = Join-Path $desktop "Hermes Agent.lnk"
    New-ShellShortcut -LnkPath $lnkPath -TargetPath "cmd.exe" -Arguments ('/k "' + $TargetBat + '"') `
        -WorkDir $WorkDir -IconLocation $IconLocation `
        -Description "Hermes Agent - Windows launcher (logo)" -WhatIf:$WhatIf
}

$root = Resolve-RepoRoot -Explicit $RepoRoot
$win = Join-Path $root "windows"

if (-not $WhatIf) {
    New-Item -ItemType Directory -Path $win -Force | Out-Null
}

$iconLoc = Get-HermesWhiteShortcutIcon -WindowsDir $win -WhatIf:$WhatIf

Write-WindowsSetupCmdBat -WindowsDir $win -WhatIf:$WhatIf
if (-not $WhatIf) { Write-Host ('[OK] ' + (Join-Path $win 'setup_hermes_windows.bat')) -ForegroundColor Green }

$openSetupSrc = Join-Path $PSScriptRoot "OPEN_SETUP.bat"
$openSetupDst = Join-Path $win "OPEN_SETUP.bat"
if (-not $WhatIf) {
    if (Test-Path -LiteralPath $openSetupSrc) {
        Copy-Item -LiteralPath $openSetupSrc -Destination $openSetupDst -Force
        Write-Host ('[OK] ' + $openSetupDst) -ForegroundColor Green
    } else {
        Write-Warning "OPEN_SETUP.bat ontbreekt in scripts\windows — wizard-snelkoppeling niet gekopieerd."
    }
}

Write-HermesUpdateCmdBat -WindowsDir $win -WhatIf:$WhatIf
if (-not $WhatIf) { Write-Host ('[OK] ' + (Join-Path $win 'hermes_update.bat')) -ForegroundColor Green }

$logoBat = Join-Path $win "Hermes_met_logo.bat"
$launchBat = Join-Path $win "launch_hermes.bat"

if ($ForceLogoBat -or -not (Test-Path -LiteralPath $logoBat)) {
    Write-LogoBat -WindowsDir $win -WhatIf:$WhatIf
    if (-not $WhatIf) { Write-Host ('[OK] Logo-launcher: ' + $logoBat) -ForegroundColor Green }
} else {
    Write-Host '[--] Logo-launcher bestaat al (gebruik -ForceLogoBat om te overschrijven).' -ForegroundColor Yellow
}

if ($ForceLaunchBat) {
    Write-MinimalLaunchBat -WindowsDir $win -RepoRootPath $root -WhatIf:$WhatIf
    if (-not $WhatIf) { Write-Host '[OK] launch_hermes.bat geschreven (-ForceLaunchBat).' -ForegroundColor Green }
} elseif (-not (Test-Path -LiteralPath $launchBat)) {
    Write-MinimalLaunchBat -WindowsDir $win -RepoRootPath $root -WhatIf:$WhatIf
    if (-not $WhatIf) { Write-Host '[OK] Minimaal launch_hermes.bat aangemaakt (was afwezig).' -ForegroundColor Green }
} else {
    Write-Host '[--] launch_hermes.bat bestaat al - niet overschreven.' -ForegroundColor Yellow
}

if (-not $NoShortcut) {
    if (Test-Path -LiteralPath $logoBat) {
        New-DesktopShortcut -TargetBat $logoBat -WorkDir $root -IconLocation $iconLoc -WhatIf:$WhatIf
        if (-not $WhatIf) {
            $desk = [Environment]::GetFolderPath("Desktop")
            Write-Host ('[OK] Snelkoppeling: ' + (Join-Path $desk 'Hermes Agent.lnk')) -ForegroundColor Green
        }
    } else {
        Write-Warning "Snelkoppeling overgeslagen: logo-bat ontbreekt."
    }
    $openBatWin = Join-Path $win "OPEN_SETUP.bat"
    if (Test-Path -LiteralPath $openBatWin) {
        $deskOs = [Environment]::GetFolderPath("Desktop")
        if ($deskOs) {
            $openLnkDesk = Join-Path $deskOs "Hermes Open Setup.lnk"
            New-ShellShortcut -LnkPath $openLnkDesk -TargetPath "cmd.exe" -Arguments ('/k "' + $openBatWin + '"') `
                -WorkDir $root -IconLocation $iconLoc `
                -Description "Hermes — volledige setup-wizard (OPEN_SETUP)" -WhatIf:$WhatIf
            if (-not $WhatIf) {
                Write-Host ('[OK] Snelkoppeling: ' + $openLnkDesk) -ForegroundColor Green
            }
        }
    }
}

if (-not $NoTaskbarLinks) {
    $setupBat = Join-Path $win "setup_hermes_windows.bat"
    $updateBat = Join-Path $win "hermes_update.bat"
    $openBatWin = Join-Path $win "OPEN_SETUP.bat"
    $setupLnk = Join-Path $win "Hermes - setup Windows - naar taakbalk slepen.lnk"
    $updateLnk = Join-Path $win "Hermes - update - naar taakbalk slepen.lnk"
    $openLnkTb = Join-Path $win "Hermes - Open Setup - naar taakbalk slepen.lnk"
    if ((Test-Path -LiteralPath $setupBat) -and (Test-Path -LiteralPath $updateBat)) {
        New-ShellShortcut -LnkPath $setupLnk -TargetPath $setupBat -Arguments "" -WorkDir $root `
            -IconLocation $iconLoc -Description "Hermes: Windows-setup (logo, snelkoppelingen)" -WhatIf:$WhatIf
        New-ShellShortcut -LnkPath $updateLnk -TargetPath $updateBat -Arguments "" -WorkDir $root `
            -IconLocation $iconLoc -Description "Hermes: update via launch_hermes.bat" -WhatIf:$WhatIf
        if (-not $WhatIf) {
            Write-Host ('[OK] Taakbalk-stijl: ' + $setupLnk) -ForegroundColor Green
            Write-Host ('[OK] Taakbalk-stijl: ' + $updateLnk) -ForegroundColor Green
        }
        if (Test-Path -LiteralPath $openBatWin) {
            New-ShellShortcut -LnkPath $openLnkTb -TargetPath $openBatWin -Arguments "" -WorkDir $root `
                -IconLocation $iconLoc -Description "Hermes: volledige setup-wizard (OPEN_SETUP.bat)" -WhatIf:$WhatIf
            if (-not $WhatIf) {
                Write-Host ('[OK] Taakbalk-stijl: ' + $openLnkTb) -ForegroundColor Green
            }
        }
    }
}

$runHermesWizard = $FullSetup -or ($env:HERMES_SETUP_FULL_SETUP -eq '1')
$batLaunchedFromCmd = ($env:HERMES_WINDOWS_BAT_PARENT -eq '1')
if ($runHermesWizard -and -not $batLaunchedFromCmd) {
    $wizExit = Invoke-HermesFullSetupWizard -RepoRoot $root -WhatIf:$WhatIf
    if ($wizExit -ne 0) { exit $wizExit }
}

$ragExtras = Join-Path $root "windows\scripts\install_rag_extras.ps1"
if ((Test-Path -LiteralPath $ragExtras) -and -not $WhatIf) {
    Write-Host ""
    Write-Host "[INFO] RAG: pip extra [rag] + MCP lancedb-knowledge..." -ForegroundColor Cyan
    try {
        & powershell -NoProfile -ExecutionPolicy Bypass -File $ragExtras -RepoRoot $root -Quiet
        Write-Host "[OK] RAG-extras (pip + MCP waar mogelijk)." -ForegroundColor Green
    } catch {
        Write-Warning "RAG-extras mislukt — handmatig: windows\scripts\install_rag_extras.ps1"
    }
}

Write-Host ""
Write-Host 'Klaar: windows\setup_hermes_windows.bat + Hermes Open Setup.lnk + Hermes - * - naar taakbalk slepen.lnk (wit icoon).' -ForegroundColor Cyan
Write-Host 'Tip: draai daarna windows\REFRESH_TASKBAR_SHORTCUTS.bat zodat ook overige Hermes-icoontjes wit update-icoon pakken als hermes_taskbar_white.ico bestaat.' -ForegroundColor DarkGray